apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: revalidator-env
  namespace: valuable-promo-prod
spec:
  encryptedData:
    REVALIDATE_TOKEN: AgAW6XLuC5efbUsnhaaSYxMgFhIHBUWQzEdFYaYqB9E+GypKVAtoZgCxgbbOcL2QWDy7sEJmyRlAO4+6hAhmhiSogooiHhBTTA2Doi9Nl51VNE+AbwN2mzeezlMT1N26Csi9dwPf20NKj9/YgMl/ZRuE37w470BkCBZ8EmwXLbFdd2mnu7TbtvIN/xO1CSjJItzArYHERh2btntqpkmjG2sL2hnbXaqfrGdDfC8CVR9yqLbSAlec1GAi5EU6S5dxV5D86cRZMR6JglbEB1VF4pW2aNUKE9vwJYNpzmJdfDWfdkF+kkeEc3qnIY8GOk2teI+p3/70G5SvdSJW5+NtKKdcxySb0zqgwQoMap6NBU+F4PwWFMIWqjJuJnzLKLKDtXQe5PRv+cXvhp+Zb3W+V5GC3HIUChwfY6etBcsXsqlbeZChybRyPglguNNwpxmq98arTYY3jEf2oAmHLIVg9qvziePOK+voiu1hxl2ISdVVDhLBJgXYfkzIpXEU/NAo4hmMeOVfQadavwwkZXNkRPVd4Ujg7EnrilQu1ZzMkNz1Pt1dTXLW3kwpQuyUBe3CqAZc4IH2YZoub/ycHUk5u/YUU6rVx5ExSqION5D88jQb80Usb+gdnw2XO6RIse1+o1DLFHFZqNTdHpVWw28F3MtV1s/Nf1jkTHr8X4zCaaLBvKTYQQuZU3EyyuHLagMSaXHEa9zUGOai5jmv1fKifI9+FMCtquRjZXtaqw8QzFhK4VJlvhkT3uE9LWANQA==
  template:
    metadata:
      creationTimestamp: null
      name: revalidator-env
      namespace: valuable-promo-prod

