---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: valuable-promo-prod
spec:
  encryptedData:
    address: AgBXI5x/pQaSORNqHE/CJEJk9pR7xfhlB75svk0PmYi4S9DEon7/P+X96+m90mJTE1KNiKJfarVzhcoGZi3wuSsI9zq7R/0W8pYKon6cjyuudRx1FgJih1iBf7oWNJNRUS9BVUjkh06SzOYO/4lVLL5g70vyebnfvuQCL+KdnWTI7Ggo1EMEvh5bdUQJz/Bd8ELjXTSuvlhpjhJhTd08obIGxk2Ni5YCW1wI24cpJ8xevCCAQ3eeY7B0aHEMFTzR6M4RHBu7dPkgzK4e46cOw+mjsHL0WAXprUmrxNbvxaweVDxBLuz49OprNKhf01OgARLieH5/CgcG3Cl3u0Wj1omJ+zyvVn3glz46soHKbPLh4YAqA55mvu9ArrGnsSwpMuhkgdBrYG0g7YP7TcNlowlbK0nCiNVISNQXW936FzfYnHXAidT46Gv3ccgQ94QrNX7DtVKydi5mTZYbSz9DwHQRU0ZZ27C35lpM4o91J3wwTTv28C9FQpSW5SSmjM4Y1UPPfKP65Xhr4WV5Vj9ahLVq9Y13IjPQ6bSmBgmdlb8MNeGjJi2EN5Y9HPljkTxQ+QsMN22CTFmj8mGDZnw8st0489GLNJvDmjtH3e9frNgyvs4iFE1lqIbqtaDrZ/ItxogrDC2Er1FZ312xU0vIKd+P5pQ1HzVuhRZYiXGiIYKMQUcFLhW1WZVTyBHEDgqoL3eIB0EhvmV6tqTx6AONolK0SQSgy6Tqvr1j8AradjvB/dI1drXBQJGaGieRtIXFsvZI8G2cEHRb++b0ldmmdoou/z0ZXZdikaOeqMOcPLXx
  template:
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: valuable-promo-prod
