apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-env
  namespace: valuable-promo-prod
data:
  NEXT_PUBLIC_STRAPI_API_URL: https://headless.valuable.promo
  NEXT_PUBLIC_STORAGE_HOST: valuable-promo-headless-prod.s3.nl-ams.scw.cloud
  SITE_URL: https://valuable.promo
  SITE_NAME: Valuable Promo
  NEXT_PUBLIC_PAGE_SIZE: '9'
  HOSTNAME: '0.0.0.0'
