---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: slack
  namespace: valuable-promo-staging
spec:
  type: slack
  channel: valuable-promo
  secretRef:
    name: slack-url
