apiVersion: apps/v1
kind: Deployment
metadata:
  name: headless-depl
  namespace: valuable-promo-staging
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headless-depl
  template:
    metadata:
      labels:
        app: headless-depl
    spec:
      containers:
        - name: headless
          image: ghcr.io/valuable-promo/headless:main-aea92f3-1688315971 # {"$imagepolicy": "valuable-promo-staging:valuable-promo-headless"}
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: headless-env
            - configMapRef:
                name: headless-env
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: valuable-promo-headless
  namespace: valuable-promo-staging
spec:
  image: ghcr.io/valuable-promo/headless
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: valuable-promo-headless
  namespace: valuable-promo-staging
spec:
  imageRepositoryRef:
    name: valuable-promo-headless
  filterTags:
    pattern: '^main-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
