---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: valuable-promo-headless
  namespace: valuable-promo-staging
spec:
  image: ghcr.io/valuable-promo/headless
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: valuable-promo-headless
  namespace: valuable-promo-staging
spec:
  imageRepositoryRef:
    name: valuable-promo-headless
  filterTags:
    pattern: '^main-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: valuable-promo-headless
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: valuable-promo
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: infra@powerkernel.com
        name: fluxcd
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  update:
    path: ./apps
    strategy: Setters
