apiVersion: apps/v1
kind: Deployment
metadata:
  name: headless-depl
  namespace: valuable-promo-staging
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headless-depl
  template:
    metadata:
      labels:
        app: headless-depl
    spec:
      containers:
        - name: headless
          image: ghcr.io/valuable-promo/headless:main # {"$imagepolicy": "valuable-promo-staging:valuable-promo-headless"}
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: headless-env
            - configMapRef:
                name: headless-env
