apiVersion: apps/v1
kind: Deployment
metadata:
  name: revalidator-depl
  namespace: valuable-promo-staging
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: revalidator-depl
  template:
    metadata:
      labels:
        app: revalidator-depl
    spec:
      serviceAccountName: revalidator
      containers:
        - name: revalidator
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
          image: ghcr.io/valuable-promo/revalidator:main-68e907f-1700353352 # {"$imagepolicy": "valuable-promo-staging:valuable-promo-revalidator"}
          imagePullPolicy: Always
          env:
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - secretRef:
                name: revalidator-env
            - configMapRef:
                name: revalidator-env
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: valuable-promo-revalidator
  namespace: valuable-promo-staging
spec:
  image: ghcr.io/valuable-promo/revalidator
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: valuable-promo-revalidator
  namespace: valuable-promo-staging
spec:
  imageRepositoryRef:
    name: valuable-promo-revalidator
  filterTags:
    pattern: '^main-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
