apiVersion: apps/v1
kind: Deployment
metadata:
  name: revalidator-depl
  namespace: valuable-promo-staging
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: revalidator-depl
  template:
    metadata:
      labels:
        app: revalidator-depl
    spec:
      serviceAccountName: revalidator
      containers:
        - name: revalidator
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
          image: ghcr.io/valuable-promo/revalidator:main-8c5a371-1716336616 # {"$imagepolicy": "valuable-promo-staging:valuable-promo-revalidator"}
          imagePullPolicy: Always
          env:
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - secretRef:
                name: revalidator-env
            - configMapRef:
                name: revalidator-env
