apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: revalidator
  namespace: valuable-promo-staging
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
