apiVersion: v1
kind: Service
metadata:
  name: revalidator-srv
  namespace: valuable-promo-staging
spec:
  selector:
    app: revalidator-depl
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
