apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-depl
  namespace: valuable-promo-staging
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-depl
  template:
    metadata:
      labels:
        app: frontend-depl
    spec:
      containers:
        - name: frontend
          image: ghcr.io/valuable-promo/frontend:main-167e9b3-1689294425 # {"$imagepolicy": "valuable-promo-staging:valuable-promo-frontend"}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: frontend-env
            - secretRef:
                name: frontend-env
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: valuable-promo-frontend
  namespace: valuable-promo-staging
spec:
  image: ghcr.io/valuable-promo/frontend
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: valuable-promo-frontend
  namespace: valuable-promo-staging
spec:
  imageRepositoryRef:
    name: valuable-promo-frontend
  filterTags:
    pattern: '^main-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
