apiVersion: batch/v1
kind: Job
metadata:
  name: pg-restore-job
  namespace: valuable-promo-prod
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: download
          image: amazon/aws-cli
          volumeMounts:
            - name: data
              mountPath: /backup
          command: ['/bin/sh']
          args:
            - '-c'
            - >
              aws s3 cp s3://$(BUCKET_NAME)/$(PG_DUMP_FILE) /backup/$(PG_DUMP_FILE)
          env:
            - name: PG_DUMP_FILE
              value: valuable_promo_prod.pgdump
          envFrom:
            - secretRef:
                name: dbbackup-env
            - configMapRef:
                name: dbbackup-env
      containers:
        - name: restore
          image: postgres:15-alpine
          volumeMounts:
            - name: data
              mountPath: /backup
          env:
            - name: PG_DUMP_FILE
              value: valuable_promo_prod.pgdump
          envFrom:
            - secretRef:
                name: dbbackup-env
            - configMapRef:
                name: dbbackup-env
          command: ['/bin/bash', '-c']
          args:
            - >
              pg_restore -Fc -h $DB_HOST -U $DB_USER -d $DB_NAME /backup/$(PG_DUMP_FILE)
      volumes:
        - name: data
          emptyDir: {}
