apiVersion: apps/v1
kind: Deployment
metadata:
  name: headless-depl
  namespace: valuable-promo-prod
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headless-depl
  template:
    metadata:
      labels:
        app: headless-depl
    spec:
      containers:
        - name: headless
          image: ghcr.io/valuable-promo/headless:v1.1.6 # {"$imagepolicy": "valuable-promo-prod:valuable-promo-headless"}
          envFrom:
            - secretRef:
                name: headless-env
            - configMapRef:
                name: headless-env
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: valuable-promo-headless
  namespace: valuable-promo-prod
spec:
  image: ghcr.io/valuable-promo/headless
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: valuable-promo-headless
  namespace: valuable-promo-prod
spec:
  imageRepositoryRef:
    name: valuable-promo-headless
  policy:
    semver:
      range: '>=0.1.0'
