apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: headless-pooler
  namespace: valuable-promo-staging
spec:
  cluster:
    name: headless-db
  instances: 1
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: '1000'
      default_pool_size: '10'
