---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: valuable-promo-staging
spec:
  encryptedData:
    password: AgCeAmM6NLSgIbQ4xBB1flB1oNy1D1nb9xDncfOCeJyuI/M3GHXMAYrKKMqE5g11AzevRUeC9cnferCybABWomCGfuA4MwCJyiwF+Fq4UTHKAb2yQlQ5jecEU4ItoJNJfIZ58DoAvA0y2eJjlj7qSP8k6TxO27MIMunKv0Bsd7DculyExL80MGMmlGAXKSbRzrG7VTDIBZZ1gz/iCyt+GJiOzaT0opSZsc82wbjC/J9ay0A1/tOApX1O30QERiS868mtQG80e9nFEWPgNs2WxRHRDeUZh/++YAwZA10NPoFsT5swzU7ILXeyXVEzj6jk7wU7ZbLDD0ST/cy8BRSJDYbOuJfEUzXwBQzFJHeV4HqeuuTCMszQOI5qQPmTtIuLBkVd72c/ZXEc9zviQ5sb+CoOCj7tb9PJWP9FllaKGKRiTyX2ehK14Wo9XyV72oMp4XkA2lZdukhnUYcq9fVlPXnG+ofPjudqjbTkoXrTrsb1uAISKIzAkmnugBEzKNW0gOlH1Bup/mA/IM8zNQeKig4XWAet50FBNjPIQXi8hCi1cJ2+WnCSeqHLYuzC8qB0Rg/lXmvNRrCQnRXj9l6MYIS5vt4Mwimeh8LurA+DG0BG0BvRlfzcBHmeJR8R36ksLo3YCdyl5lNBjVQH2cPDX9LJovr57Zkp5m+HUIpsdWf0mGrScN6UVaG1aZJnOMOXc1DlPsgTkIdnGdL0TEpIH5zXLDS+RggF8sDQUgZT3Kud3q3/xd5YtuY+LqgF5g==
    username: AgAhu/5S2IIBX8YLPR7ueljA8X7uQsspxak8vL0VpPV1UEcQ0AURY+fk4yDHxJ3sKNq/RhqVQHOKwi1VJwGWtfTOMUeDSnJbMW85B+oxOBa8yQiAsOaXrf6nbcnWk+pVhYt7c7/RVsAmUaVFI7FTxwchbPD+CY6nny2VGlpY7r37Z3y7YfQEw46dJx7f/ytAbB7ahSZR2llR4kIhkkRG2AulDyx7zn4V8ug9KdZDPYObt93ucARO1fRLK1+3cvTj3a09YwS1mnsh0CT1ljHRO1vkWOri0EGKAwK/OHfedMg9YBQ9n3sdb9Zv1HrBSmN5oVMxV+DB3W5kXvgR7mDumInC+XPJoBe1sS2Jnx/8b7DarBP25DxbU6P2bu15Z/G4aAozrPrf+uqy1T7ATArs1LyrtjVWHUZ4nXhFzXSj5WCm5q883EZcowQ0tXRFBlqW15VHYhYAKkd2Qrd/sKHGugBJ4bz11ePkNrBAeTfne6d/SdiLWzCftnw1UCPkR6Mz3j/waODt3RUV0YV7RqQzC2ebiG685WlRn8XdXF5E2dywoOEaa9icseReMxVt3QV2ZNzgY6XM8eOtlDPXZ4tGafLnGLAbfWxfQ9ZUP46sbeuIqsgK8TC3qmugvEA0bZrFk7C/ar1H4eQNYBEWLxJXLq3dpP1uhnlALNQ6xv4vpnajZWHvVGwvnM94BFQTH3x6C99Ykvo=
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: valuable-promo-staging
