apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: continuous-deployment
  namespace: valuable-promo-staging
subjects:
  - kind: ServiceAccount
    name: github-actions
roleRef:
  kind: Role
  name: continuous-deployment
  apiGroup: rbac.authorization.k8s.io
