apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dbbackup-env
  namespace: valuable-promo-prod
spec:
  encryptedData:
    AWS_SECRET_ACCESS_KEY: AgAXsRmIZ0Xnsg+8j5FCuCs8KEqrN8Z2Lk0Sb+esqk7DL4QCvW8jkV4ePqHpES4Jx+zSr9XaxhZx9TJJuDHqCaTijT7iWDL8HkUwC8SDaIGL5ojjCMXhPtbbkbyxqT+x8CSoUZU7hwJzjFzOZicqykqNvBxsEf1wAuPRvDrCuxFa43gflygu2Zdcn1HwpBaq3MqlmSb/bwFVp8Xp8uidYX8tT4QNRwfiZ0y/M1xTYgqfOHRU5C2NPUy5lsTjvoU4RFJF1oMJiGJy5VbJXldrwRQ2tpce5WyuMqmyJhjvlAP8AxFFkihQT9pGedD7cJYNns2moSUwNZj0u+X0SHv80XQld3+jKqTiHAtG93GASwStYcex7XExQaRPeFaFBaOsyImc5nxjc/S3khxoMLDLsmS1BpxaU9fbDn9zjjEGgR/6XDCVsbc0piqZYWMi8b/7Fm8bUPCWzX+o+qTME4WVdxU3v5/iOkTkV8kRzq92+VaC8xfLne5cL+S+zady33Sp+oFhPdpyQGc8Nc9I7kkKRwSU8jErq1Oa2gKbGm1z9GeRSheTQFUOsFLyM+LCTYNkwGLPafwkcSC1afaVdVGVeBYDvLejGolpIg62sZS448v6SAynFcAuC1svsolYYHhBi4+/lemB2HPDa2Vc06PQupXQ4+zfT6nX0/CG86/wZ8Xtu5m0B+9BrXgsaXzHhOsfaUR4tMkHWlaDEYJ51kJ2+g2PghnMOQCy4GKIO/0QL6RXy18Vc1M=
    PGPASSWORD: AgCF3wXDKwGAG94iO9cuti/CK7FswA7CtD/i3aix0gKwBaqGITfCtIFt8bxl/suNjPJcwusLb3oZa/2uH5/0D+pTKlK4x/R6HRSH8in+uDi9wu7FodTto/utYhsxZbUESeYb/2j2ZsYYJLF5VEz1nO6RBDlPFS1CppO4ovE+S89OFwvkYPBVTyFrvHffgQqwafVy0XnVGxaCqmkjAn4lqPi2zTNGDWXEtPbyVavcVjaN4lfBSI8hOfOHxVQp2aeLrKkxz7kMPHaem2Ms0s7XkCdrcF+y1EjJf4mV2zReMojsVTWd0+fuECMazVdkXY8HsbJtq0gn6NjGOwtH0oHPep3tCT1IY12GldBWvOR0N1y/bI7DwKeaWmWN2xjQjjUAP8RUu0OsKVwbY2gTpDGFvDyW+MAOd/3nMr0w4LSMguOAvzPhaQJ1Ro1rSMBjdjRNvhzvGHWkWjjy/0fqhV+Cf0bqmGPxAF8S0VwEpM8cVENX7h/waPcenM/CWe3ZeMD7pBCPYJRAMSVEV+tG7UlSZch8ZhasBGLLtKB5DYUgxPPdv/WYeA10XyMQ0U1543wVvd6uhjOzc6JYnk0sbIH8RpbIpNeF77QO/6/Jp8DVdSfkaZNNsvdaOsiiw1s9zyGrZwA/90rqFIrhUQZ2TEGB/jBJnxlUTHYQoqysSLbRSYLv3G2cS2t2q7EihdGoxynEtolohSPboSozRcJWUdrzh96oQqnpRKgcq11w4lmRkD0VKg==
  template:
    metadata:
      creationTimestamp: null
      name: dbbackup-env
      namespace: valuable-promo-prod

