apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-depl
  namespace: valuable-promo-staging
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-depl
  template:
    metadata:
      labels:
        app: frontend-depl
    spec:
      containers:
        - name: frontend
          image: ghcr.io/valuable-promo/frontend:main-adbfa12-1710975181 # {"$imagepolicy": "valuable-promo-staging:valuable-promo-frontend"}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: frontend-env
            - secretRef:
                name: frontend-env
