---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frontend-env
  namespace: valuable-promo-staging
spec:
  encryptedData:
    REVALIDATE_TOKEN: AgDN6urIWKmeVxnpd6zUXZXrYAPdYaQHoT6Oa6q6chaX3YtY486UcEsntUPc7sSFiYWv9zq42jryd89Y0Nvwns+tuqMBLvSjgfjqwDEXKMGB+fzSwSRSj/6ANwQtOsZksxOKbMHA4KhG2I4BzqsAN7tC04f6qtUyqwIT+RuHgPdi6BdCg2hoklbtR8nOftTz1c8xpIH3QWkvl9lcz5MUrIlo73judNQ1VblgCfyNp/fAoDP5pjjnqIvGsFJKkXFsGWhx/+QIfv3YaIXASW5On4/NdEkY2z3U/1utwd+ABGtcvInyWqCsjupC/zI7tBH+iikp128P37G/yoc3b/fK6GJCz2IDlT3kx/eL0ad1JzfLHrPtL5K7TXoqwXUDZfEWnBDSLX+bLPhG1JrChuYMPCKW1Tx7cM5YZ6QcDL+DbutF+LtkWhC3s3SUnZg9Tt1gZEqjxTTWrz7OGK3oICU7L3Ijqw/00HgYIK5+iIWbVcGrKBsPkic98yELT6X2pJ77Arnmp6PzkyXNk8CVrRKv58AO8ksciR8yZ2Wa9L52YiqyQ0bIQjyvmKFe4Y+3CAi13jXcuyB8FWUuDcpyX91Nqu80c8UjruSk/A5BDMllmtmxy3Ig9SMfyAe9frkBr+fqth54pGHeiIYly+jC+zNgSjQid7vZC0GcBPkJ1DoZAGVfzUEJKewz/NwcJC03ZsT1F3XvzI2DOMV+jLmJET91o53rOp3R2HT66+1xrv4VqTZUw8O/IaRRvF4hfwvkHQ==
  template:
    metadata:
      creationTimestamp: null
      name: frontend-env
      namespace: valuable-promo-staging
