apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dbbackup-env
  namespace: valuable-promo-staging
spec:
  encryptedData:
    AWS_SECRET_ACCESS_KEY: AgAQNc6wTp9SCdEzr580caQL0W3cdsLaPxVgPwnZVWPG1Z+VqbrspuSDuwd0Va+jRNXafn0F78e0/TIT7+qE8fDfx9Epr+5Kgb+g4HPz1EzaqWDq9xp4AfaXPp2wBBJGa5aPWWK2xARBHMFDsKwKo+54e4yDpcyAeIorYcicuve9ISCvUBnha+VVk525ogJZcGeZQPCkcpvCfRFBcv9i3HFpQ3J9rkKTX/Q2Snu/XBCQbDq50NgFQPJIxDIkj6Ujse5b1SLsRWqdmCB92XmWAO9ZLVtAKsIVesZhgNygQhzcELICRSUVp2NDruPS5FTAmX7hs3L5q2baxzKgWsC806Sype6Axb8391t5NoHoleyvdvYPsrQ8Z53sXndSSRjbXmUMs8QeLssvUW6OLlyJ1AWx8u2Bxj1qJL+2IgSfcQr0yehPCX52noCTlp5WUmy033Ig36Wl10SRVVLlOTJ+neULTw9WNa+3C0I0e6LUyUuzLrNsbZdjPGSUTlWmIVSVE7cwvd5KoozOC2hARhGcb+j0pZ1tYqvgQ3Lk+9QNv7DwvxPbN3lF7uNUuC0ezn20t/KbnQmAz//5zgqBYe/g1paHcIMJvV9DCXkopMi36oI+n1zh/QL42VRV4CvRg1VTHMVP8wv40m/vH5pN1tnE9RsVEM6CDKUIt17BE+GRng2Nh2AF1Trk1pFxDexj1XuTXfayuDXKLQREzREj+ONUiA1MJfBSlkDJpqJ/MXS+esxSaYFwMto=
    PGPASSWORD: AgAOc1Y7u4RfXm1X/YuvSHjFBvsIW344N1nnSqPOAYhWSCu35EYUokc4aAVfB5DrfWnnAUw1kq/ivjgDCxjJh+HnGTR/7fNiN0mdCY3+iegkviPGuDysOAVgCJYwCFcvryshpF3GruKS9VqQFefd+o5KUmmEFnQRqvkRXk1Di2XRU98cxH5i4M/EOJNfZN111C4Ikijb3lm5gEn1Q8mU1mT/m/58nILufeubrSMNiLkPP/xcArXa+MZ3vsmoIAjWpkfiZp6F3ZLSsngrRIYcfI+udsUYeyHjUfERBe8XY9ejqvHjztnoaqgER2Pml1fuYNW/8cxPr1328jz5bAuod2rC8VZFE9O0cIGg4fxwpuzZaGFfmEK5MdG83uwDZh2r+HRyXN0ax5aeUlisvIEVwWZdPuo5aLPMkKlV29wLzIX5RWQ8/p/y7SQ35Nb8JM4YypLywMLtWCiHzvPnDLUR+Sj/Ah+KN1mMn1XmsVbMGw+Fk+h0WsLAMvCT1nfm9+Sh5rmW4LYRC+Dn8IDi2HvgCF9zqtssrhAlSMcPCu16blDaAu5IkJl94cMiOu+lJlPGGbaytwBJVhUaIj1H4153O1emOLP/3vz1n30MErKhyzsuY3KDsTOKIRFAdsAbTv0YGhLt1nd0uhGCh4dBlAOm9Iw2LaS6QSokf6U2niUggcFRsBrE/51i3Qaq7vipyWh4dk5G28w9xNKcJQKLyvGMRqdJdYm0ARPS9GWsRwRQrW51EA==
  template:
    metadata:
      creationTimestamp: null
      name: dbbackup-env
      namespace: valuable-promo-staging

