apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: headless-db
  namespace: valuable-promo-prod
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1
  instances: 1
  postgresql:
    parameters:
      max_worker_processes: '60'
    pg_hba:
      - host all all all md5
  storage:
    size: 5Gi
  primaryUpdateMethod: switchover
