---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: valuable-promo-prod
spec:
  encryptedData:
    password: AgA7qp2tz3FURDxwCuz7VrPoFYgsKPYe/C2lhb66BUPuFCSaLETq5py6FzjtAkW009uoKVZDiYz8XqFwibLQZn+aiilQHvuYLDyX0fn93+xwMHLUFB3LYgHic6kL9Xiu4glYvLdCgeAE6l2pCYf7fYKLZmpBSjwnX4EPUAOHLkBPE/SO2OSz+fz9nNxCA9u5zQmGngsTtjAcQcF/M5mRG7UBQUksHzzfkVmSnhwDzhXGXiy1zEjhhX3CTUhBBeHthBfqXFSX9bWxiALdOKYv+viS9h4PoyaKYbeZgIPiAnX6b5nZ2Hg4nBvg/fNTmSQhJfT8KwRsIFYQcr8TQNXDrP5p0egTpY9GZTnbiQkKmFthA5xg4hAfFEU2KKxPKcmmImfkDwEDmL3i0njfmtQuR0q8OFBEk46cI4pcHO3cuybZBdiedkO+fd4zJJtakssrl4KjskmQqMYFK/eUdYgfM3sz0FHXXt42feA7mHIGUWINPFNPhfC+hDOpaK1r9U7NfKUMHzW0SFLwDuB07GqWh6sP1iPsM5Wdc1L8Z9mF5ntsQByAwLApiQ1LolT+tP45GUJBvmUv8HGVMmwEwQ6sF7cv5yCxYbkeGVg0GCBO0cZx0lYLK0DSlwz1IvuuLPKRC1VgAwPdcFfDEMZ+NapwOp7OyecgAr0kmM/c3IMYgO+7k/I5bW2oXnTtqCUIT9NyDjxoQOfT24bhJ5klQVs5Q4jg+EECsN4Y95o+XBwpzx3ioHHJxriDC4ch22imtw==
    username: AgCLa5C4exrpKHO5ZAi2YFJ2ka46ogsef3yNj+TgkJBE9VLqzYV//3oTLIcmETnqYARJbUCHlu/OUdkKX0nDXN83YNwyGioQ6VRp4vW7hiX+5SaeOLvlm4UvPg1Tldldz6eMgkf/JohmDpbexGvmrO/SJeOw8nJBjS4QwDwlc7LY6wKW2F6obp+Ku2SKhY9/oyvQoh499azreUzSz3fUrENAA0fJ31gdeWdsCe0zkxBi7HVMPLuEOAdpAOZXjuc5wt3+Op4P6bGh3tDNBEnlDSJ3Y01OxQqMgJ9wo6hzq+ezuvLGUlMe+h1sT76CuCizR6fNxUNyx9Fy1ZCuFisRYZenWmKxy4gAXrrWZy1syHN8PVYtXM4B8BbrHPWDU7NRUfqprQq/TB1DliOQ3HYm4wLwtPS6IMCv+sPurRU5mvolPn88Yf1lQ0ut5bHjAvZTjofC9s29JXr+aGPfb3w7reHDixTKpkspS3L16xiN4ZmG8Wx63/BtlSSmWbhH03EplAJNvKG0ch/fsMoJgw6dCYqXm0OJddyvx7/ZMycw+kqgWmOf+jPey0TdMI9gnAxIXBxBfzMe+mE6QUSie/4CJGA0UoDQmjVSVNvyjaSc/6s7l5SBnzEqr/oukW+TNi93wy/6soMeuKmq7HdW74XuhTMnbqURz1bBREN4qVYEEOLr87W2IJ0bjWEtdkeffwk/HKUnzOQ=
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: valuable-promo-prod
